"""produccion 7 fases qr limite

Revision ID: 0aa114401beb
Revises: 3f8c2d91a6e4
Create Date: 2026-09-03 01:10:32.186066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0aa114401beb'
down_revision: Union[str, None] = '3f8c2d91a6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controles_calidad', sa.Column('aprobado', sa.Boolean(),
                                                    server_default=sa.true(),
                                                    nullable=False))
    op.add_column('garments', sa.Column('codigo_qr', sa.String(length=60), nullable=True))
    op.add_column('garments', sa.Column('fecha_limite_entrega', sa.Date(), nullable=True))
    op.add_column('garments', sa.Column('paso_confeccion', sa.Boolean(),
                                        server_default=sa.false(), nullable=False))
    op.create_index(op.f('ix_garments_codigo_qr'), 'garments', ['codigo_qr'], unique=True)
    op.add_column('pruebas_entalle', sa.Column('notas_sastre', sa.Text(), nullable=True))
    op.add_column('pruebas_entalle', sa.Column('fotos', sa.JSON(), nullable=True))
    # Remap al vocabulario canónico de 7 fases
    op.execute("UPDATE garments SET estado_taller='POR_CORTAR' WHERE estado_taller IN "
               "('pendiente','diseno','patronaje','pausado')")
    op.execute("UPDATE garments SET estado_taller='EN_CORTE' WHERE estado_taller='corte'")
    op.execute("UPDATE garments SET estado_taller='ARMADO_HILVAN' WHERE estado_taller IN "
               "('confeccion','en_proceso')")
    op.execute("UPDATE garments SET estado_taller='EN_PRUEBA' WHERE estado_taller IN "
               "('fitting_1','prueba_1')")
    op.execute("UPDATE garments SET estado_taller='EN_CONFECCION', paso_confeccion=1 "
               "WHERE estado_taller IN ('ajustes','fitting_2')")
    op.execute("UPDATE garments SET estado_taller='ACABADOS' WHERE estado_taller IN "
               "('terminados','calidad','terminado')")
    op.execute("UPDATE garments SET estado_taller='CALIDAD_OK' WHERE estado_taller='listo'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pruebas_entalle', 'fotos')
    op.drop_column('pruebas_entalle', 'notas_sastre')
    op.drop_index(op.f('ix_garments_codigo_qr'), table_name='garments')
    op.drop_column('garments', 'paso_confeccion')
    op.drop_column('garments', 'fecha_limite_entrega')
    op.drop_column('garments', 'codigo_qr')
    op.drop_column('controles_calidad', 'aprobado')
    # ### end Alembic commands ###
