"""modulo aislado cierre jornada taller

Revision ID: 43e95b0f14bc
Revises: c076bc9cb82e
Create Date: 2026-09-02 22:53:53.120452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43e95b0f14bc'
down_revision: Union[str, None] = 'c076bc9cb82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _bind = op.get_bind()
    _insp = sa.inspect(_bind)
    _ex_tables = set(_insp.get_table_names())
    _ex_cols = {t: {c["name"] for c in _insp.get_columns(t)} for t in _ex_tables}
    _ex_idxs = {t: {i["name"] for i in _insp.get_indexes(t)} for t in _ex_tables}
    if 'taller_tareas' not in _ex_tables:
        op.create_table('taller_tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('tarifa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    if 'ix_taller_tareas_descripcion' not in _ex_idxs.get('taller_tareas', set()):
        op.create_index(op.f('ix_taller_tareas_descripcion'), 'taller_tareas', ['descripcion'], unique=False)
    if 'taller_cierres_jornada' not in _ex_tables:
        op.create_table('taller_cierres_jornada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('producto_referencia', sa.String(length=160), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('total_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'ix_taller_cierres_jornada_fecha' not in _ex_idxs.get('taller_cierres_jornada', set()):
        op.create_index(op.f('ix_taller_cierres_jornada_fecha'), 'taller_cierres_jornada', ['fecha'], unique=False)
    if 'ix_taller_cierres_jornada_user_id' not in _ex_idxs.get('taller_cierres_jornada', set()):
        op.create_index(op.f('ix_taller_cierres_jornada_user_id'), 'taller_cierres_jornada', ['user_id'], unique=False)
    if 'taller_cierre_detalle' not in _ex_tables:
        op.create_table('taller_cierre_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cierre_id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('tarifa_aplicada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cierre_id'], ['taller_cierres_jornada.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['taller_tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'ix_taller_cierre_detalle_cierre_id' not in _ex_idxs.get('taller_cierre_detalle', set()):
        op.create_index(op.f('ix_taller_cierre_detalle_cierre_id'), 'taller_cierre_detalle', ['cierre_id'], unique=False)
    if 'ix_taller_cierre_detalle_tarea_id' not in _ex_idxs.get('taller_cierre_detalle', set()):
        op.create_index(op.f('ix_taller_cierre_detalle_tarea_id'), 'taller_cierre_detalle', ['tarea_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taller_cierre_detalle_tarea_id'), table_name='taller_cierre_detalle')
    op.drop_index(op.f('ix_taller_cierre_detalle_cierre_id'), table_name='taller_cierre_detalle')
    op.drop_table('taller_cierre_detalle')
    op.drop_index(op.f('ix_taller_cierres_jornada_user_id'), table_name='taller_cierres_jornada')
    op.drop_index(op.f('ix_taller_cierres_jornada_fecha'), table_name='taller_cierres_jornada')
    op.drop_table('taller_cierres_jornada')
    op.drop_index(op.f('ix_taller_tareas_descripcion'), table_name='taller_tareas')
    op.drop_table('taller_tareas')
    # ### end Alembic commands ###
