"""configuracion sede + 6 ambitos

Revision ID: 60288cb5be04
Revises: 9c2ab41f0e77
Create Date: 2026-09-03 00:22:37.598775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '60288cb5be04'
down_revision: Union[str, None] = '9c2ab41f0e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion')
    # ### end Alembic commands ###
