"""taller prod ficha pruebas calidad

Revision ID: 66330a0d74a9
Revises: 43e95b0f14bc
Create Date: 2026-09-02 23:31:58.184251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66330a0d74a9'
down_revision: Union[str, None] = '43e95b0f14bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controles_calidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controles_calidad_garment_id'), 'controles_calidad', ['garment_id'], unique=False)
    op.create_table('pruebas_entalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.Column('numero_prueba', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('correcciones', sa.JSON(), nullable=True),
    sa.Column('observaciones_ajuste', sa.Text(), nullable=True),
    sa.Column('foto_path', sa.String(length=255), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pruebas_entalle_garment_id'), 'pruebas_entalle', ['garment_id'], unique=False)
    op.add_column('garments', sa.Column('artesano_id', sa.Integer(), nullable=True))
    op.add_column('garments', sa.Column('diseno', sa.JSON(), nullable=True))
    # NOTA SQLite: el FK artesano->users se crea en la revisión siguiente
    # (batch recreate, ya que SQLite no soporta ADD CONSTRAINT).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garments', 'diseno')
    op.drop_column('garments', 'artesano_id')
    op.drop_index(op.f('ix_pruebas_entalle_garment_id'), table_name='pruebas_entalle')
    op.drop_table('pruebas_entalle')
    op.drop_index(op.f('ix_controles_calidad_garment_id'), table_name='controles_calidad')
    op.drop_table('controles_calidad')
    # ### end Alembic commands ###
