"""frontoffice turnos caja

Revision ID: 7b058dc99ab3
Revises: 7d1e9a02c4b5
Create Date: 2026-09-03 00:58:43.911835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b058dc99ab3'
down_revision: Union[str, None] = '7d1e9a02c4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _bind = op.get_bind()
    _insp = sa.inspect(_bind)
    _ex_tables = set(_insp.get_table_names())
    _ex_cols = {t: {c["name"] for c in _insp.get_columns(t)} for t in _ex_tables}
    _ex_idxs = {t: {i["name"] for i in _insp.get_indexes(t)} for t in _ex_tables}
    if 'caja_turnos' not in _ex_tables:
        op.create_table('caja_turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('saldo_apertura', sa.Float(), nullable=False),
    sa.Column('saldo_cierre_teorico', sa.Float(), nullable=True),
    sa.Column('saldo_cierre_real', sa.Float(), nullable=True),
    sa.Column('fecha_apertura', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if 'ix_caja_turnos_estado' not in _ex_idxs.get('caja_turnos', set()):
        op.create_index(op.f('ix_caja_turnos_estado'), 'caja_turnos', ['estado'], unique=False)
    if 'ix_caja_turnos_usuario_id' not in _ex_idxs.get('caja_turnos', set()):
        op.create_index(op.f('ix_caja_turnos_usuario_id'), 'caja_turnos', ['usuario_id'], unique=False)
    if 'turno_id' not in _ex_cols.get('cash_movements', set()):
        op.add_column('cash_movements', sa.Column('turno_id', sa.Integer(), nullable=True))
    if 'ix_cash_movements_turno_id' not in _ex_idxs.get('cash_movements', set()):
        op.create_index(op.f('ix_cash_movements_turno_id'), 'cash_movements', ['turno_id'], unique=False)
    # NOTA SQLite: FK cash->turno va en revisión batch aparte.
    if 'tela_reservada' not in _ex_cols.get('garments', set()):
        op.add_column('garments', sa.Column('tela_reservada', sa.Boolean(),
                                        server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garments', 'tela_reservada')
    op.drop_index(op.f('ix_cash_movements_turno_id'), table_name='cash_movements')
    op.drop_column('cash_movements', 'turno_id')
    op.drop_index(op.f('ix_caja_turnos_usuario_id'), table_name='caja_turnos')
    op.drop_index(op.f('ix_caja_turnos_estado'), table_name='caja_turnos')
    op.drop_table('caja_turnos')
    # ### end Alembic commands ###
