"""localizacion peru docs identidad

Revision ID: c076bc9cb82e
Revises: f5030ae14a8e
Create Date: 2026-09-02 22:18:11.742848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c076bc9cb82e'
down_revision: Union[str, None] = 'f5030ae14a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('tipo_doc', sa.String(length=12), nullable=False))
    op.add_column('clients', sa.Column('nro_doc', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('distrito', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_clients_nro_doc'), 'clients', ['nro_doc'], unique=False)
    op.add_column('companies', sa.Column('distrito', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'distrito')
    op.drop_index(op.f('ix_clients_nro_doc'), table_name='clients')
    op.drop_column('clients', 'distrito')
    op.drop_column('clients', 'nro_doc')
    op.drop_column('clients', 'tipo_doc')
    # ### end Alembic commands ###
