"""localizacion peru docs identidad

Revision ID: c076bc9cb82e
Revises: f5030ae14a8e
Create Date: 2026-09-02 22:18:11.742848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c076bc9cb82e'
down_revision: Union[str, None] = 'f5030ae14a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(conn, table: str, column: str) -> bool:
    return any(c["name"] == column for c in sa.inspect(conn).get_columns(table))


def _has_index(conn, table: str, name: str) -> bool:
    return any(i["name"] == name for i in sa.inspect(conn).get_indexes(table))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotente: la DB de desarrollo ya puede traer estas columnas
    # (create_all) con el sello alembic aún en el baseline.
    conn = op.get_bind()
    if not _has_column(conn, "clients", "tipo_doc"):
        op.add_column('clients', sa.Column('tipo_doc', sa.String(length=12), nullable=True,
                                           server_default="DNI"))
        op.execute(sa.text("UPDATE clients SET tipo_doc='DNI' WHERE tipo_doc IS NULL"))
    if not _has_column(conn, "clients", "nro_doc"):
        op.add_column('clients', sa.Column('nro_doc', sa.String(length=20), nullable=True))
    if not _has_column(conn, "clients", "distrito"):
        op.add_column('clients', sa.Column('distrito', sa.String(length=100), nullable=True))
    if not _has_index(conn, "clients", "ix_clients_nro_doc"):
        op.create_index(op.f('ix_clients_nro_doc'), 'clients', ['nro_doc'], unique=False)
    if not _has_column(conn, "companies", "distrito"):
        op.add_column('companies', sa.Column('distrito', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'distrito')
    op.drop_index(op.f('ix_clients_nro_doc'), table_name='clients')
    op.drop_column('clients', 'distrito')
    op.drop_column('clients', 'nro_doc')
    op.drop_column('clients', 'tipo_doc')
    # ### end Alembic commands ###
