"""comercial unificado pipeline

Revision ID: df3f2939eea3
Revises: 60288cb5be04
Create Date: 2026-09-03 00:51:36.824739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df3f2939eea3'
down_revision: Union[str, None] = '60288cb5be04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interacciones_client_id'), 'interacciones', ['client_id'], unique=False)
    op.create_index(op.f('ix_interacciones_company_id'), 'interacciones', ['company_id'], unique=False)
    op.create_index(op.f('ix_interacciones_lead_id'), 'interacciones', ['lead_id'], unique=False)
    op.add_column('appointments', sa.Column('garment_id', sa.Integer(), nullable=True))
    # NOTA SQLite: el FK garment->garments va en revisión batch aparte.
    op.add_column('clients', sa.Column('clasificacion', sa.String(length=20),
                                       server_default='Nuevo', nullable=False))
    op.add_column('companies', sa.Column('clasificacion', sa.String(length=20),
                                         server_default='Nuevo', nullable=False))
    op.add_column('leads', sa.Column('canal', sa.String(length=30), nullable=True))
    op.add_column('leads', sa.Column('motivo_perdida', sa.String(length=255), nullable=True))
    # Remap de vocabularios legacy -> pipeline unificado
    op.execute("UPDATE leads SET estado='PROSPECTO' WHERE estado='nuevo'")
    op.execute("UPDATE leads SET estado='CITA_AGENDADA' WHERE estado='contactado'")
    op.execute("UPDATE leads SET estado='COTIZACION_ENVIADA' WHERE estado='cotizado'")
    op.execute("UPDATE leads SET estado='GANADO_EN_TALLER' WHERE estado='ganado'")
    op.execute("UPDATE leads SET estado='PERDIDO' WHERE estado='perdido'")
    op.execute("UPDATE appointments SET tipo='TOMA_MEDIDAS' WHERE tipo='toma_medidas'")
    op.execute("UPDATE appointments SET tipo='PRIMERA_PRUEBA' WHERE tipo='primera_prueba'")
    op.execute("UPDATE appointments SET tipo='SEGUNDA_PRUEBA' WHERE tipo='segunda_prueba'")
    op.execute("UPDATE appointments SET tipo='ENTREGA_FINAL' WHERE tipo='entrega'")
    op.execute("UPDATE appointments SET tipo='AJUSTE' WHERE tipo='ajuste'")
    op.execute("UPDATE appointments SET estado='PROGRAMADA' WHERE estado='programada'")
    op.execute("UPDATE appointments SET estado='CONFIRMADA' WHERE estado='confirmada'")
    op.execute("UPDATE appointments SET estado='ASISTIO' WHERE estado='realizada'")
    op.execute("UPDATE appointments SET estado='CANCELADA' WHERE estado='cancelada'")
    op.execute("UPDATE appointments SET estado='NO_ASISTIO' WHERE estado='no_asistio'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'motivo_perdida')
    op.drop_column('leads', 'canal')
    op.drop_column('companies', 'clasificacion')
    op.drop_column('clients', 'clasificacion')
    op.drop_column('appointments', 'garment_id')
    op.drop_index(op.f('ix_interacciones_lead_id'), table_name='interacciones')
    op.drop_index(op.f('ix_interacciones_company_id'), table_name='interacciones')
    op.drop_index(op.f('ix_interacciones_client_id'), table_name='interacciones')
    op.drop_table('interacciones')
    # ### end Alembic commands ###
