"""baseline ERP ampliado

Revision ID: f5030ae14a8e
Revises: 
Create Date: 2026-09-02 22:10:07.373918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f5030ae14a8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
